from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any, Protocol

from botocore.exceptions import BotoCoreError, ClientError, ConnectTimeoutError, ReadTimeoutError

from app.models import SummaryType


class BedrockClientUnavailableError(RuntimeError):
    """Raised when no local summary provider is enabled."""


class BedrockClientResponseError(RuntimeError):
    """Raised when the provider response does not satisfy the SDK contract."""


@dataclass(frozen=True)
class BedrockRequest:
    system_prompt: str
    user_message: str
    prompt_version: str
    model_id: str
    summary_type: SummaryType
    allowed_evidence: tuple[str, ...]
    include_recommendations: bool


@dataclass(frozen=True)
class BedrockResult:
    text: str
    input_tokens: int
    output_tokens: int
    total_tokens: int
    latency_ms: int
    model_id: str


class BedrockClient(Protocol):
    def converse(self, request: BedrockRequest) -> BedrockResult: ...


class BedrockRuntimeClient(Protocol):
    def converse(self, **kwargs: Any) -> dict[str, Any]: ...


class DisabledBedrockClient:
    def converse(self, request: BedrockRequest) -> BedrockResult:
        del request
        raise BedrockClientUnavailableError("AI summary provider is unavailable")


class FakeBedrockClient:
    """Deterministic local test double; it is not a foundation-model inference."""

    def converse(self, request: BedrockRequest) -> BedrockResult:
        evidence = list(request.allowed_evidence)
        label = "Technical" if request.summary_type is SummaryType.TECHNICAL else "Executive"
        if evidence:
            summary = f"{label} synthetic summary based on {len(evidence)} observed fact(s)."
            causes = [
                {
                    "description": "The available facts require operator investigation.",
                    "confidence": "low",
                    "supporting_evidence": [evidence[0]],
                }
            ]
        else:
            summary = f"{label} synthetic summary with insufficient incident context."
            causes = []

        payload = {
            "summary": summary,
            "probable_causes": causes,
            "recommended_actions": (
                ["Review the observed facts and collect missing operational evidence."]
                if request.include_recommendations
                else []
            ),
            "missing_information": (
                ["Additional incident context is required."] if len(evidence) < 4 else []
            ),
            "limitations": [
                "Generated by FakeBedrockClient for local synthetic-data testing; no model was invoked."
            ],
        }
        text = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        input_tokens = len(request.user_message) // 4 + 1
        output_tokens = len(text) // 4 + 1
        return BedrockResult(
            text=text,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            total_tokens=input_tokens + output_tokens,
            latency_ms=1,
            model_id=request.model_id,
        )


class BedrockConverseClient:
    """Synchronous adapter for an injected Amazon Bedrock Runtime client."""

    def __init__(
        self,
        runtime_client: BedrockRuntimeClient,
        *,
        max_tokens: int,
        temperature: float,
    ) -> None:
        self._runtime_client = runtime_client
        self._max_tokens = max_tokens
        self._temperature = temperature

    def converse(self, request: BedrockRequest) -> BedrockResult:
        try:
            response = self._runtime_client.converse(
                modelId=request.model_id,
                system=[{"text": request.system_prompt}],
                messages=[
                    {
                        "role": "user",
                        "content": [{"text": request.user_message}],
                    }
                ],
                inferenceConfig={
                    "maxTokens": self._max_tokens,
                    "temperature": self._temperature,
                },
            )
        except (ConnectTimeoutError, ReadTimeoutError) as exc:
            raise TimeoutError("Amazon Bedrock Runtime request timed out") from exc
        except (BotoCoreError, ClientError) as exc:
            raise BedrockClientUnavailableError(
                "Amazon Bedrock Runtime request failed"
            ) from exc

        try:
            content = response["output"]["message"]["content"]
            text_blocks = [
                block["text"]
                for block in content
                if isinstance(block, dict) and isinstance(block.get("text"), str)
            ]
            usage = response["usage"]
            input_tokens = usage["inputTokens"]
            output_tokens = usage["outputTokens"]
            total_tokens = usage["totalTokens"]
            latency_ms = response["metrics"]["latencyMs"]
            stop_reason = response["stopReason"]
        except (KeyError, TypeError) as exc:
            raise BedrockClientResponseError(
                "Amazon Bedrock Runtime returned an invalid response"
            ) from exc

        if not text_blocks or not all(
            type(value) is int and value >= 0
            for value in (input_tokens, output_tokens, total_tokens, latency_ms)
        ):
            raise BedrockClientResponseError(
                "Amazon Bedrock Runtime returned an invalid response"
            )
        if total_tokens != input_tokens + output_tokens or stop_reason != "end_turn":
            raise BedrockClientResponseError(
                "Amazon Bedrock Runtime returned an invalid response"
            )
        if any(not block for block in text_blocks):
            raise BedrockClientResponseError(
                "Amazon Bedrock Runtime returned an invalid response"
            )

        return BedrockResult(
            text="".join(text_blocks),
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            total_tokens=total_tokens,
            latency_ms=latency_ms,
            model_id=request.model_id,
        )
