from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Protocol

from app.models import SummaryType


class BedrockClientUnavailableError(RuntimeError):
    """Raised when no local summary provider is enabled."""


@dataclass(frozen=True)
class BedrockRequest:
    system_prompt: str
    user_message: str
    prompt_version: str
    model_id: str
    summary_type: SummaryType
    allowed_evidence: tuple[str, ...]
    include_recommendations: bool


@dataclass(frozen=True)
class BedrockResult:
    text: str
    input_tokens: int
    output_tokens: int
    latency_ms: int
    model_id: str


class BedrockClient(Protocol):
    def converse(self, request: BedrockRequest) -> BedrockResult: ...


class DisabledBedrockClient:
    def converse(self, request: BedrockRequest) -> BedrockResult:
        del request
        raise BedrockClientUnavailableError("AI summary provider is unavailable")


class FakeBedrockClient:
    """Deterministic local test double; it is not a foundation-model inference."""

    def converse(self, request: BedrockRequest) -> BedrockResult:
        evidence = list(request.allowed_evidence)
        label = "Technical" if request.summary_type is SummaryType.TECHNICAL else "Executive"
        if evidence:
            summary = f"{label} synthetic summary based on {len(evidence)} observed fact(s)."
            causes = [
                {
                    "description": "The available facts require operator investigation.",
                    "confidence": "low",
                    "supporting_evidence": [evidence[0]],
                }
            ]
        else:
            summary = f"{label} synthetic summary with insufficient incident context."
            causes = []

        payload = {
            "summary": summary,
            "probable_causes": causes,
            "recommended_actions": (
                ["Review the observed facts and collect missing operational evidence."]
                if request.include_recommendations
                else []
            ),
            "missing_information": (
                ["Additional incident context is required."] if len(evidence) < 4 else []
            ),
            "limitations": [
                "Generated by FakeBedrockClient for local synthetic-data testing; no model was invoked."
            ],
        }
        text = json.dumps(payload, sort_keys=True, separators=(",", ":"))
        input_tokens = len(request.user_message) // 4 + 1
        output_tokens = len(text) // 4 + 1
        return BedrockResult(
            text=text,
            input_tokens=input_tokens,
            output_tokens=output_tokens,
            latency_ms=1,
            model_id=request.model_id,
        )
